recsys/urls.py
from django.contrib import admin
from django.urls import path, include
from videorecapp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('videorecapp/', include('videorecapp.urls')),
    path('logout', views.user_logout, name='logout'),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]

videorecapp/urls.py
from django.urls import path, re_path

from . import views

app_name = 'videorecapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('recommendations/', views.recommendations, name='recommendations'),
    path('contact/', views.contact, name='contact'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('send_email/', views.send_email, name='send_email'),
    path('video_list/', views.video_list, name='video_list'),
]

videorecapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional fields
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username


class Video(models.Model):
    """
    defines a video record retrieved from YouTube:
    """
    yt_video_id = models.CharField(max_length=100, unique=True)
    title = models.CharField(max_length=105, unique=False, null=False)
    embed_url = models.URLField(max_length=100, null=True)

videorecapp/forms.py
from django import forms
from django.contrib.auth.models import User
from videorecapp.models import UserProfileInfo


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password')
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'email': 'Email',
            'username': 'Username',
            'password': 'Password',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'comment_input'}),
            'last_name': forms.TextInput(attrs={'class': 'comment_input'}),
            'email': forms.EmailInput(attrs={'class': 'comment_input'}),
            'username': forms.TextInput(attrs={'class': 'comment_input'}),
            'password': forms.PasswordInput(attrs={'class': 'comment_input'}),
        }


class UserProfileInfoForm(forms.ModelForm):

    class Meta:
        model = UserProfileInfo
        fields = ('profile_pic',)
        labels = {
            'profile_pic': 'Profile picture'
        }


class ContactForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'comment_input'}), label='Name')
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'comment_input'}), label='Return email')
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'comment_input'}), label='Message')


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.PasswordInput()

videorecapp/views.py
from django.conf import settings
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.db import transaction
from django.db import IntegrityError
from django.db import connection
from django.core.mail import send_mail
from videorecapp import yt_actions
from videorecapp.forms import UserForm, UserProfileInfoForm, ContactForm
from videorecapp.models import Video, User
from videorecapp.colaborative_filtering import prepare_dataset, user_recommendations
from star_ratings.models import Rating


def index(request):
    total_users = User.objects.all().count()
    total_videos = Video.objects.all().count()
    total_ratings = Rating.objects.all().count()
    return render(request, 'videorecapp/index.html', {
        'total_users': total_users,
        'total_videos': total_videos,
        'total_ratings': total_ratings,
    })


def recommendations(request):
    get_user_ids_query = (
        "SELECT id "
        "FROM auth_user "
        "ORDER BY id ASC;"
    )
    get_anonymous_recommendations = ("SELECT title, embed_url "
                      "FROM videorecapp_video v "
                      "INNER JOIN star_ratings_rating r ON v.id=r.object_id "
                      "WHERE r.average=5"
                      )
    if request.user.is_authenticated:
        # create DB connection
        cursor = connection.cursor()
        # get all user ids
        cursor.execute(get_user_ids_query)
        result = list(cursor.fetchall())
        user_ids = [list(x)[0] for x in result]
        dataset = {}
        for user_id in user_ids:
            result = prepare_dataset(user_id)
            user_result = {}
            for key,value in result:
                user_result[key] = value
            dataset[user_id] = user_result
        recommended_for_user = user_recommendations(dataset, request.user.id)
        if recommended_for_user:
            get_user_recommendations = ("SELECT title, embed_url "
                                        "FROM videorecapp_video v "
                                        "WHERE id IN ({0})"
                                        ).format(','.join(str(video) for video in recommended_for_user))
            cursor.execute(get_user_recommendations)
            recommended = cursor.fetchall()
            return render(request, 'videorecapp/recommendations.html', {
                'range': range(15),
                'recommended': recommended
            })
        else:
            cursor.execute(get_anonymous_recommendations)
            recommended = cursor.fetchall()
            return render(request, 'videorecapp/recommendations.html', {'range': range(15), 'recommended': recommended})
    else:
        cursor = connection.cursor()
        cursor.execute(get_anonymous_recommendations)
        recommended = cursor.fetchall()
        return render(request, 'videorecapp/recommendations.html', {'range': range(15), 'recommended': recommended})


def contact(request):
    contact_form = ContactForm()
    return render(request, 'videorecapp/contact.html', {'contact_form': contact_form})


def register(request):

    registered = False

    if request.method == 'POST':

        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'videorecapp/register.html',
                  {
                      'user_form': user_form,
                      'profile_form': profile_form,
                      'registered': registered,
                  })


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('videorecapp:index'))
            else:
                return HttpResponse('Account not active')
        else:
            print('*' * 20)
            print('Someone tried to login and failed!')
            print('Username: {0}\nPassword: {0}'.format(username, password))
            print('*' * 20)
            return HttpResponse('Invalid login credentials supplied!')
    else:
        return render(request, 'videorecapp/login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('videorecapp:index'))


def login_form(request):
    form = UserForm()
    return render(request, 'videorecapp/login.html', {'form': form})


@login_required
def video_list(request):
    if request.method == 'POST':
        search_query = request.POST.get('search_query')
        # second argument for youtube_search is the number of videos to retrieve
        videos = yt_actions.youtube_search(search_query, '15')
        fetched_videos = []
        fetched_video_ids = []
        # create a list of fetched videos as instances of Video model for further DB insert
        for video_id, video_data in videos.items():
            new_video_id = video_id
            fetched_video_ids.append(new_video_id)
            new_video_title = video_data['title']
            new_video_embed_url = video_data['embed_url']
            new_video = Video(yt_video_id=new_video_id, title=new_video_title, embed_url=new_video_embed_url)
            fetched_videos.append(new_video)
        # bulk save of all fetched_videos to DB
        bulk_save(fetched_videos)
        # get the video objects from DB
        videos_to_display = Video.objects.filter(yt_video_id__in=fetched_video_ids)
        return render(request, 'videorecapp/search.html', {'fetched_videos': videos_to_display})


def send_email(request):
    '''
    if request.method == 'POST':
        contact_form = ContactForm(data=request.POST)
        if contact_form.is_valid():
            subject = 'RecSys: Contact form feedback'
            from_email = settings.EMAIL_HOST_USER
            to_email = ['mellon211195@gmail.com']
            message = contact_form.cleaned_data['message']
            send_mail(subject=subject, from_email=from_email, recipient_list=to_email, message=message, fail_silently=False)
    '''
    return HttpResponseRedirect(reverse('videorecapp:index'))


def bulk_save(queryset):
    for item in queryset:
        try:
            with transaction.atomic():
                item.save()
        except IntegrityError:
            print('Duplicate entry found - {0}'.format(item.yt_video_id))

templates/videorecapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
   <head>
    <title>Video Recommendations</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="RecSys project">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/static/styles/bootstrap4/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/plugins/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/static/styles/main_styles.css">
    {% block head %}
        <!-- static files for each page here -->
    {% endblock %}
   </head>
   <body>
      <div class="super_container">
         <!-- Header -->
         <header class="header">
            <!-- Top Bar -->
            <div class="top_bar">
               <div class="top_bar_container">
                  <div class="container">
                     <div class="row">
                        <div class="col">
                           <div class="top_bar_content d-flex flex-row align-items-center justify-content-start">
                              <ul class="top_bar_contact_list">
                                 <li>
                                    <div class="question">Have any questions?</div>
                                 </li>
                                 <li>
                                    <i class="fa fa-envelope-o" aria-hidden="true"></i>
                                    <div>andrii.kovtun@study.sumdu.edu.ua</div>
                                 </li>
                              </ul>
                              <div class="top_bar_login ml-auto">
                                 <div class="login_button"><a href="{% url 'videorecapp:register' %}">Register</a></div>
                                 {% if user.is_authenticated %}
                                     <div class="login_button"><a href="{% url 'logout' %}">Logout</a></div>
                                     <div id="uname" class="login_button"><em>Welcome, <strong>{{ user.username }}</strong>!</em></div>
                                 {% else %}
                                     <div class="login_button"><a href="{% url 'videorecapp:user_login' %}">Login</a></div>
                                 {% endif %}
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <!-- Header Content -->
            <div class="header_container">
               <div class="container">
                  <div class="row">
                     <div class="col">
                        <div class="header_content d-flex flex-row align-items-center justify-content-start">
                           <div class="logo_container">
                              <a href="{% url 'videorecapp:index' %}">
                                 <div id="top" class="logo_text">Rec<span>Sys</span></div>
                              </a>
                           </div>
                           <nav class="main_nav_contaner ml-auto">
                              <ul class="main_nav">
                                 {% url 'videorecapp:index' as url_index %}
                                 {% url 'videorecapp:recommendations' as url_vrec %}
                                 {% url 'videorecapp:contact' as url_contact %}
                                 <li {% if request.path == url_index %} class="active" {% endif %}><a href="{% url 'videorecapp:index' %}">Home</a></li>
                                 <li {% if request.path == url_vrec %} class="active" {% endif %}><a href="{% url 'videorecapp:recommendations' %}">Personal Recommendations</a></li>
                                 <li {% if request.path == url_contact %} class="active" {% endif %}><a href="{% url 'videorecapp:contact' %}">Contact</a></li>
                              </ul>
                           </nav>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </header>

         {% block content %}
            <!-- content for each page here -->
         {% endblock %}

         <!-- Footer -->
         <footer class="footer">
            <div class="footer_background" style="background-image:url(/static/images/footer_background.png)"></div>
            <div class="container">
               <div class="row footer_row">
                  <div class="col">
                     <div class="footer_content">
                        <div class="row">
                           <div class="col-lg-3 footer_col">
                              <!-- Footer About -->
                              <div class="footer_section footer_about">
                                 <div class="footer_logo_container">
                                    <a href="#">
                                       <div class="footer_logo_text">Rec<span>Sys</span></div>
                                    </a>
                                 </div>
                                 <div class="footer_about_text">
                                    <p>The best website for providing video recommendations.</p>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-3 footer_col">
                              <!-- Footer Contact -->
                              <div class="footer_section footer_contact">
                                 <div class="footer_title">Contact Us</div>
                                 <div class="footer_contact_info">
                                    <ul>
                                       <li>andrii.kovtun@study.sumdu.edu.ua</li>
                                       <li>+(380) 111 22 33</li>
                                       <li>2, Rymskogo-Korsakova st., 40007 Sumy, Ukraine</li>
                                    </ul>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-3 footer_col">
                              <!-- Footer links -->
                              <div class="footer_section footer_links">
                                 <div class="footer_title">Navigate</div>
                                 <div class="footer_links_container">
                                    <ul>
                                       <li><a href="{% url 'videorecapp:index' %}">Home</a></li>
                                       <li><a href="{% url 'videorecapp:recommendations' %}">Personal Recommendations</a></li>
                                       <li><a href="{% url 'videorecapp:contact' %}">Contact</a></li>
                                    </ul>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="row copyright_row">
                  <div class="col">
                     <div class="copyright d-flex flex-lg-row flex-column align-items-center justify-content-start">
                        <div class="cr_text">
                           <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                           Copyright &copy;
                           <script>document.write(new Date().getFullYear());</script>
                           All rights reserved | This template is made with
                           <i class="fa fa-heart-o" aria-hidden="true"></i> by
                           <a href="https://colorlib.com" target="_blank">Colorlib</a>
                           <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </footer>
      </div>
      <script src="/static/js/jquery-3.2.1.min.js"></script>
      <script src="/static/styles/bootstrap4/popper.js"></script>
      <script src="/static/styles/bootstrap4/bootstrap.min.js"></script>
      <script src="/static/plugins/greensock/TweenMax.min.js"></script>
      <script src="/static/plugins/greensock/TimelineMax.min.js"></script>
      <script src="/static/plugins/scrollmagic/ScrollMagic.min.js"></script>
      <script src="/static/plugins/greensock/animation.gsap.min.js"></script>
      <script src="/static/plugins/greensock/ScrollToPlugin.min.js"></script>
      <script src="/static/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
      <script src="/static/plugins/easing/easing.js"></script>
      <script src="/static/plugins/parallax-js-master/parallax.min.js"></script>
      <script src="/static/js/custom.js"></script>
   </body>
</html>

templates/videorecapp/contact.html
{% extends 'videorecapp/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/contact.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/contact_responsive.css' %}">
{% endblock %}

{% block content %}
<!-- Home -->
<div class="home">
   <div class="breadcrumbs_container">
      <div class="container">
         <div class="row">
            <div class="col">
               <div class="breadcrumbs">
                  <ul>
                     <li><a href="{% url 'videorecapp:index' %}">Home</a></li>
                     <li>Contact</li>
                  </ul>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- Contact -->
<div class="contact">
   <!-- Contact Info -->
   <div class="contact_info_container">
      <div class="container">
         <div class="row">
            <!-- Contact Form -->
            <div class="col-lg-6">
               <div class="contact_form">
                  <div class="contact_info_title">Contact Form</div>
                  <form action="{% url 'videorecapp:send_email' %}" class="comment_form" method="post">
                      {% csrf_token %}
                      {% for field in contact_form %}
                          <div>
                            <label for="{{ field.id_for_label }}" class="form_title">{{ field.label_tag }}</label>
                            {{ field }}
                          </div>
                      {% endfor %}
                      <div>
                         <button type="submit" class="comment_button trans_200">submit</button>
                     </div>
                  </form>
               </div>
            </div>
            <!-- Contact Info -->
            <div class="col-lg-6">
               <div class="contact_info">
                  <div class="contact_info_title">Contact Info</div>
                  <div class="contact_info_text">
                     <p>
                         Feel free to use contact form to leave a feedback about RecSys,
                         share your comments or suggest improvements.
                     </p>
                  </div>
                  <div class="contact_info_location">
                     <div class="contact_info_location_title">Sumy Office</div>
                     <ul class="location_list">
                        <li>2, Rymskogo-Korsakova st., 40007 Sumy, Ukraine</li>
                        <li>Phone:  +(380) 111 22 33</li>
                        <li>Email: andrii.kovtun@study.sumdu.edu.ua</li>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}

templates/videorecapp/index.html
{% extends 'videorecapp/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/main_styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/responsive.css' %}">
{% endblock%}

{% block content %}
<!-- Home -->
<div class="home">
   <div class="home_slider_container">
      <!-- Home Slider -->
      <div class="owl-carousel owl-theme home_slider">
         <!-- Home Slider Item -->
         <div class="owl-item">
            <div id="home_sb" class="home_slider_background"></div>
            <div class="home_slider_content">
               <div class="container">
                  <div class="row">
                     <div class="col text-center">
                        <div class="home_slider_title">Video Recommendations</div>
                        <div class="home_slider_subtitle">Explore, Watch, Rate</div>
                        <div class="home_slider_form_container">
                           <form action="{% url 'videorecapp:video_list' %}" method="post" id="home_search_form_1" class="home_search_form d-flex flex-lg-row flex-column align-items-center justify-content-between">
                              <div class="d-flex flex-row align-items-center justify-content-start">
                                 <input type="search" class="home_search_input" name="search_query" placeholder="Video search by keyword" required="required">
                              </div>
                               {% csrf_token %}
                              <button type="submit" class="home_search_button">search</button>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- Features -->
<div class="features">
   <div class="container">
      <div class="row">
         <div class="col">
            <div class="section_title_container text-center">
               <h2 class="section_title">Welcome To RecSys</h2>
               <div class="section_subtitle">
                  <p>A simple video recommendations website</p>
               </div>
            </div>
         </div>
      </div>
      <div class="row features_row">
         <!-- Features Item -->
         <div class="col-lg-3 feature_col">
            <div class="feature text-center trans_400">
               <div class="feature_icon"><img src="/static/images/icon-search.png" alt=""></div>
               <h3 class="feature_title">Search</h3>
               <div class="feature_text">
                  <p>Search videos by keywords</p>
               </div>
            </div>
         </div>
         <!-- Features Item -->
         <div class="col-lg-3 feature_col">
            <div class="feature text-center trans_400">
               <div class="feature_icon"><img src="/static/images/icon-watch.png" alt=""></div>
               <h3 class="feature_title">Watch</h3>
               <div class="feature_text">
                  <p>Watch the videos</p>
               </div>
            </div>
         </div>
         <!-- Features Item -->
         <div class="col-lg-3 feature_col">
            <div class="feature text-center trans_400">
               <div class="feature_icon"><img src="/static/images/icon-rate.png" alt=""></div>
               <h3 class="feature_title">Rate</h3>
               <div class="feature_text">
                  <p>Rate the video to build further recommendations</p>
               </div>
            </div>
         </div>
         <!-- Features Item -->
         <div class="col-lg-3 feature_col">
            <div class="feature text-center trans_400">
               <div class="feature_icon"><img src="/static/images/icon-browse.png" alt=""></div>
               <h3 class="feature_title">Browse</h3>
               <div class="feature_text">
                  <p>Check the recommended videos based on your interests</p>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- Counter -->
<div class="counter">
   <div class="counter_background" style="background-color: #F5F5F5"></div>
   <div class="container">
      <div class="row">
         <div class="col-lg-12">
            <div class="counter_content">
               <h2 class="counter_title">Register Now</h2>
               <!-- Milestones -->
               <div class="milestones d-flex flex-md-row flex-column align-items-center justify-content-between">
                  <!-- Milestone -->
                  <div class="milestone">
                     <div class="milestone_counter" data-end-value="2">0</div>
                     <div class="milestone_text">months</div>
                  </div>
                  <!-- Milestone -->
                  <div class="milestone">
                     <div class="milestone_counter" data-end-value="{{ total_users }}">0</div>
                     <div class="milestone_text">users</div>
                  </div>
                  <!-- Milestone -->
                  <div class="milestone">
                     <div class="milestone_counter" data-end-value="{{ total_videos }}">0</div>
                     <div class="milestone_text">videos</div>
                  </div>
                  <!-- Milestone -->
                  <div class="milestone">
                     <div class="milestone_counter" data-end-value="{{ total_ratings }}">0</div>
                     <div class="milestone_text">ratings</div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}

templates/videorecapp/login.html
{% extends 'videorecapp/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/contact.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/contact_responsive.css' %}">
{% endblock %}

{% block content %}
<!-- Home -->
<div class="home">
   <div class="breadcrumbs_container">
      <div class="container">
         <div class="row">
            <div class="col">
               <div class="breadcrumbs">
                  <ul>
                     <li><a href="{% url 'videorecapp:index' %}">Home</a></li>
                     <li>Login</li>
                  </ul>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- Login -->
<div class="contact">
   <!-- Login Info -->
   <div class="contact_info_container">
      <div class="container">
         <div class="row">
            <!-- Login Form -->
            <div class="col-lg-6">
               <div class="contact_form">
                  <div class="contact_info_title">Login Form</div>
                  <form action="{% url 'videorecapp:user_login' %}" class="comment_form" method="post">
                      {% csrf_token %}
                     <div>
                        <label class="form_title" for="user_name">Username</label>
                        <input type="text" class="comment_input" id="user_name" name="username" required="required" placeholder="Enter username...">
                     </div>
                     <div>
                        <label class="form_title" for="user_password">Password</label>
                        <input type="password" class="comment_input" id="user_password" name="password" required="required" placeholder="Enter password...">
                     </div>
                     <div>
                        <button type="submit" class="comment_button trans_200">submit</button>
                     </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}